name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'

    - name: Install test requirements
      run: python -m pip install --upgrade pytest hatchling  && python -m pip install --upgrade --pre yt-dlp

    - name: Run tests
      run: |
        python -m pytest