name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'

    - name: Install test requirements
      run: python -m pip install --upgrade pytest hatchling yt-dlp@https://github.com/seproDev/yt-dlp/archive/refs/heads/pass_po_token.zip

    - name: Run tests
      run: |
        python -m pytest